name: "AWS CR Build"
description: "AWS CR Build"
inputs:
  url: 
    description: "url server"
    required: true
  namespacetag: 
    description: "namespacetag name"
    required: true
  namespace: 
    description: "namespace name"
    required: true
  imagename: 
    description: "image name"
    required: true
  buildnr: 
    description: "build nr"
    required: true
  tag:
    description: "tag"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
    - ${{ inputs.namespacetag }}
    - ${{ inputs.namespace }}
    - ${{ inputs.imagename }}
    - ${{ inputs.buildnr }}
    - ${{ inputs.tag }}
branding:
  color: 'green'
  icon: 'at-sign'
