#!/bin/sh
set -e

REGISTRY_URL=$1
NAMESPACE_TAG=$2
REGISTRY_NAMESPACE=$3
IMAGE_NAME=$4
BUILD_NUMBER=$5
TAG=$6


echo -e "Variables de entorno de compilación:"
echo "REGISTRY_URL=${REGISTRY_URL}"
echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
echo "IMAGE_NAME=${IMAGE_NAME}"
echo "BUILD_NUMBER=${BUILD_NUMBER}"
echo "TAG=${TAG}"


aws ecr get-login-password  | docker login --username AWS --password-stdin $REGISTRY_URL

#docker build -f $DOCKERFILE -t $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER .

#docker push $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER

docker pull $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER

docker tag $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER $REGISTRY_URL/$NAMESPACE_TAG/$IMAGE_NAME:$TAG

docker push $REGISTRY_URL/$NAMESPACE_TAG/$IMAGE_NAME:$TAG
